export const PROMPTS = [
    "Main Character Energy",
    "Touch Grass",
    "Cringe",
    "Slay",
    "Gatekeep",
    "Gaslight",
    "Girlboss",
    "POV: You're Late",
    "Spilling Tea",
    "Ghosting",
    "Red Flag",
    "Green Flag",
    "Icks",
    "Situationship",
    "Parasocial Relationship",
    "Doomscrolling",
    "Thirst Trap",
    "Influencer in the Wild",
    "Vibe Check",
    "Living Rent Free",
    "Core Memory",
    "Fever Dream",
    "Villain Arc",
    "Canon Event",
    "NPC Behavior",
    "Golden Retriever Energy",
    "Black Cat Energy",
    "iPad Kid",
    "Academic Weapon",
    "Rizz God",
    "Skibidi Toilet",
    "Grimace Shake",
    "Barbenheimer",
    "Roman Empire",
    "Girl Dinner",
    "Beige Flag",
    "Delulu is the Solulu",
    "Emotional Support Water Bottle",
    "Healing Inner Child",
    "Manifesting",
    "Quiet Luxury",
    "Old Money Aesthetic",
    "Y2K Fashion",
    "Coquette Bows",
    "Stanley Cup",
    "AirPods Max",
    "Dyson Airwrap",
    "Matcha Latte",
    "Avocado Toast",
    "Iced Coffee Addiction",
    "Cheugy",
    "Simp",
    "No Cap",
    "Bet",
    "Sus",
    "Yeet"
];

export const getRandomPrompt = (exclude: string[] = []) => {
    const available = PROMPTS.filter(p => !exclude.includes(p));
    if (available.length === 0) return PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
    return available[Math.floor(Math.random() * available.length)];
};
