-- Remove existing prompts to refresh the vibe
DELETE FROM public.prompts;

-- Insert new Gen Z and Object-focused prompts
INSERT INTO public.prompts (text, category) VALUES
('Bucket Hat', 'fashion'),
('Fanny Pack', 'fashion'),
('AirPods', 'tech'),
('Iced Coffee', 'food'),
('Avocado Toast', 'food'),
('Hydro Flask', 'object'),
('Crocs', 'fashion'),
('Bubble Tea', 'food'),
('Ring Light', 'tech'),
('Gaming Chair', 'object'),
('Game Controller', 'object'),
('Oversized Hoodie', 'fashion'),
('Chunky Sneakers', 'fashion'),
('Electric Scooter', 'object'),
('Drone', 'tech'),
('VR Headset', 'tech'),
('Smart Watch', 'tech'),
('Tote Bag', 'fashion'),
('Yoga Mat', 'object'),
('Succulent', 'nature'),
('Cactus', 'nature'),
('Pizza Slice', 'food'),
('Burger', 'food'),
('Taco', 'food'),
('Sushi Roll', 'food'),
('Glazed Donut', 'food'),
('Matcha Latte', 'food'),
('Acai Bowl', 'food'),
('Ramen Bowl', 'food'),
('Dumpling', 'food'),
('Blue Cap', 'object'),
('Ghost', 'spooky'),
('Spilling Tea', 'action'),
('Clown Face', 'funny'),
('Skull', 'spooky'),
('Fire', 'abstract'),
('Sparkles', 'abstract'),
('Rocket Ship', 'object'),
('The Moon', 'nature'),
('Stonks Graph', 'funny'),
('Doge', 'meme'),
('Crewmate', 'gaming'),
('Impostor', 'gaming'),
('TikTok Logo', 'app'),
('Selfie', 'action'),
('Podcast Mic', 'object'),
('Cat Ear Headphones', 'tech'),
('Mechanical Keyboard', 'tech'),
('Anime Eyes', 'art'),
('Vibing Cat', 'meme'),
('Pikachu', 'gaming'),
('Pokeball', 'gaming'),
('Minecraft Block', 'gaming'),
('Diamond Sword', 'gaming'),
('Victory Royale', 'gaming'),
('Stanley Cup', 'object'),
('Puffer Jacket', 'fashion'),
('Mullet', 'fashion'),
('Disposable Camera', 'object'),
('Flip Phone', 'tech'),
('Tamagotchi', 'tech'),
('Game Boy', 'tech'),
('Fidget Spinner', 'object'),
('Slay', 'slang'),
('Main Character Energy', 'slang'),
('Touch Grass', 'slang'),
('Cringe', 'slang'),
('Simp', 'slang'),
('Ratio', 'slang'),
('Based', 'slang'),
('Mid', 'slang'),
('Caught in 4k', 'slang'),
('Bet', 'slang'),
('Glow Up', 'slang'),
('Vibes', 'slang'),
('Sus', 'slang');
