-- Remove all existing prompts
DELETE FROM public.prompts;

-- Insert the 50 Default Prompt Pack items
INSERT INTO public.prompts (text, category) VALUES
('Hot air balloon', 'default'),
('Bicycle', 'default'),
('Crocodile', 'default'),
('Lighthouse', 'default'),
('Coffee mug', 'default'),
('Train engine', 'default'),
('Turtle', 'default'),
('Backpack', 'default'),
('Windmill', 'default'),
('Apple', 'default'),
('Old-school camera', 'default'),
('Elephant', 'default'),
('Umbrella', 'default'),
('Bridge', 'default'),
('Cat', 'default'),
('Desk lamp', 'default'),
('Castle', 'default'),
('Goldfish', 'default'),
('Bus', 'default'),
('Pizza slice', 'default'),
('Penguin', 'default'),
('Alarm clock', 'default'),
('Helicopter', 'default'),
('Frog', 'default'),
('Keychain', 'default'),
('Statue', 'default'),
('Horse', 'default'),
('Water fountain', 'default'),
('Game controller', 'default'),
('Ice cream cone', 'default'),
('Parrot', 'default'),
('Car', 'default'),
('Owl', 'default'),
('Book', 'default'),
('Pyramid', 'default'),
('Sneakers', 'default'),
('Dog', 'default'),
('Wind chime', 'default'),
('Banana', 'default'),
('Clock tower', 'default'),
('Desk fan', 'default'),
('Rocket', 'default'),
('Sandwich', 'default'),
('Tortoise', 'default'),
('Chair', 'default'),
('Bridge with arches', 'default'),
('Street light', 'default'),
('Boat', 'default'),
('Spoon', 'default'),
('Wind-up toy', 'default');

-- Add used_prompts column to rooms table if it doesn't exist
ALTER TABLE public.rooms 
ADD COLUMN IF NOT EXISTS used_prompts TEXT[] DEFAULT '{}';
